In [1]:
import numpy as np 
import pandas as pd
import time
import ast
import dask.dataframe as dd
from qdrant_client import QdrantClient
from qdrant_client import models
from scipy.sparse import hstack, csr_matrix
from sklearn.preprocessing import normalize

api_key= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6MGU0NGM3MDktZGIzOC00YTEzLWFjOWYtNzE3OTU5N2RlNzFkIn0.rlseqT8NBMyg4AvVaY0liD4U22KkNR8708gb8uvP-Qs",


url= "https://2ac22e98-018d-4349-820e-51e45fe1a5d9.us-west-1-0.aws.cloud.qdrant.io",

git hub

vaibhavpatel5586@gmail.com

 url= "https://7ab9b2c2-c912-4d3d-968e-5b5667c7dd2f.us-east-1-1.aws.cloud.qdrant.io",
api_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6MTgzZThhZWEtZjM3ZS00OWI1LWExZDgtYmFhOWU5MzhkOTAzIn0.VSK4oW8M3JLR58zjwIupP3dtHeODPUjdOcVmKoIzOzE",

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = dd.read_csv("cleaned_metadata1.csv", converters={
    'genres': ast.literal_eval,
    'studios': ast.literal_eval, 
    "title": ast.literal_eval,
}, keep_default_na=False)
users = dd.read_csv(
    'ratings11.csv', 
    dtype={
        'userID': 'int32',       # 1 byte instead of 8
        'rating': 'int8',
        "id" : "int32" 
    }
)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [7]:
user.compute()

          userID  rating  mal_url
0             24       5       20
1             24       7       30
2             24       8       32
3             24       7       71
4             24       5      198
...          ...     ...      ...
4112748  1774511       9     1575
4112749  1774511       9     6547
4112750  1774511       9    10793
4112751  1774511       8     1535
4112752  1774511       8     2993

[21160897 rows x 3 columns]

In [4]:
total_users = users.loc[:,"userID"].nunique().compute()

In [5]:
total_animes = users.loc[:,"mal_url"].nunique().compute()

In [6]:
unique_users = users['userID'].unique().compute().tolist()
unique_animes = users["mal_url"].unique().compute().tolist()

In [11]:
user.info

<bound method DataFrame.info of Dask DataFrame Structure:
              userID rating mal_url
npartitions=5
               int64  int64   int64
                 ...    ...     ...
...              ...    ...     ...
                 ...    ...     ...
                 ...    ...     ...
Dask Name: to_string_dtype, 2 expressions
Expr=ArrowStringConversion(frame=FromMapProjectable(aefbb00))>

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 155839 entries, 0 to 155838
Data columns (total 20 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               155839 non-null  int64
 1   idMal            155839 non-null  int64
 2   title            155839 non-null  object
 3   type             155839 non-null  str
 4   format           155839 non-null  str
 5   status           155839 non-null  str
 6   seasonYear       155839 non-null  float64
 7   episodes         155839 non-null  float64
 8   chapters         155839 non-null  float64
 9   volumes          155839 non-null  float64
 10  averageScore     155839 non-null  float64
 11  popularity       155839 non-null  int64
 12  trending         155839 non-null  int64
 13  description      155839 non-null  str
 14  genres           155839 non-null  object
 15  studios          155839 non-null  object
 16  isAdult          155839 non-null  bool
 17  source           155839 non-null  str
 18  countryOfOrigin  155839 non-null  str
 19  stats            155839 non-null  int64
dtypes: bool(1), float64(5), int64(5), object(3), str(6)
memory usage: 53.4+ MB

In [4]:

# users2 = users.sort_values(by= "id")
rating = users[["id" , "userID", "rating"]].compute()

In [5]:
# rating = rating.reset_index(drop= True)
rating = rating.sort_values(by=['id', 'userID'])

In [30]:
rating

             id   userID  rating
11            1        1      10
103           1        2      10
173           1        3      10
467           1        6       7
648           1       12      10
...         ...      ...     ...
2893004  207215  1668394       8
1266976  207215  1716906       7
1395710  207215  1719777       7
2135223  207215  1736680       8
981265   207221  1540706       9

[70472220 rows x 3 columns]

In [6]:
rating = rating[rating["rating"] != 0]

            id   userID  rating
0          431        1      10
1         1535        1      10
2        15315        1       7
3        14345        1      10
4        11757        1      10
...        ...      ...     ...
3811582   1887  1774522       7
3811583   2605  1774522       7
3811584  13663  1774522       7
3811585   9181  1774522       6
3811586     59  1774522       5

[70472220 rows x 3 columns]

### making a sparse matrix

In [7]:
from scipy.sparse import csr_matrix

# Create mappings for mal_url and userID to matrix indices
animeId_map = {url: i for i, url in enumerate(rating['id'].unique())}
user_map = {uid: i for i, uid in enumerate(rating['userID'].unique())}

# Map to indices
row_indices = rating['id'].map(animeId_map)
col_indices = rating['userID'].map(user_map)
values = rating['rating'].values

# Create sparse matrix (rows = mal_urls, cols = users)
sparse_matrix = csr_matrix(
    (values, (row_indices, col_indices)),
    shape=(len(animeId_map), len(user_map))
)

print(sparse_matrix.shape)  # (unique mal_urls, unique users)
print(f"Non-zero entries: {sparse_matrix.nnz}")
print(f"Density: {sparse_matrix.nnz / (sparse_matrix.shape[0] * sparse_matrix.shape[1]):.6f}")

(16560, 999986)
Non-zero entries: 70456812
Density: 0.004255

In [8]:
# normalize each row to unit length so dot product = cosine similarity
sparse_matrix = normalize(sparse_matrix, norm='l2')

In [30]:
# connecting with client 
client = QdrantClient(
    url= "https://7ab9b2c2-c912-4d3d-968e-5b5667c7dd2f.us-east-1-1.aws.cloud.qdrant.io",
    api_key= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6MTgzZThhZWEtZjM3ZS00OWI1LWExZDgtYmFhOWU5MzhkOTAzIn0.VSK4oW8M3JLR58zjwIupP3dtHeODPUjdOcVmKoIzOzE",
    prefer_grpc= True,
    timeout= 120.0
)
collection  = "collaborative"

In [32]:
client.create_collection(
    collection_name=collection,
    # vectors_config is for dense vectors. Set to empty dict if ONLY using sparse.
    vectors_config={}, 
    sparse_vectors_config={
        # "text-sparse" is the name of the vector. You will use this name when inserting.
        "users_ratings": models.SparseVectorParams(
            index=models.SparseIndexParams(
                on_disk = True,          # storing indexing on the disk instead of ram , because the data is too large 
            ),
            modifier= models.Modifier.NONE    
        )
    }
)

True

In [10]:
# Invert animeId_map: row_index → actual MAL anime id
row_to_mal = {row_idx: mal_id for mal_id, row_idx in animeId_map.items()}

anime_points = []

for row_idx in range(sparse_matrix.shape[0]):
    row    = sparse_matrix.getrow(row_idx)   # called only once
    mal_id = row_to_mal[row_idx]

    point = models.PointStruct(
        id      = int(mal_id),
        vector  = {"users_ratings": models.SparseVector(
            indices = row.indices.tolist(),
            values  = row.data.tolist()
        )},
        payload = {"mal_id": int(mal_id)}
    )
    anime_points.append(point)

In [33]:


def safe_upsert(client, collection_name, points, batch_size=10, max_retries=10, start_from=0):
    total_batches = (len(points) + batch_size - 1) // batch_size
    
    for i in range(start_from, len(points), batch_size):
        batch = points[i:i + batch_size]
        batch_num = i // batch_size
        retries = 0
        success = False
        
        while not success and retries <= max_retries:
            try:
                client.upsert(
                    collection_name=collection_name,
                    points=batch,
                    wait=True   # wait for confirmation before next batch
                )
                print(f"Batch {batch_num}/{total_batches} uploaded ({i} to {i + len(batch)})")
                success = True
                time.sleep(2)  # breathing room between successful batches
                
            except Exception as e:
                retries += 1
                if retries > max_retries:
                    print(f"Failed at batch {batch_num} after {max_retries} retries. Re-run with start_from={i}")
                    raise e
                
                wait_time = min(5 * (2 ** (retries - 1)), 300)  # 5s, 10s, 20s... capped at 5 min
                print(f"Error on batch {batch_num}: {e}")
                print(f"Waiting {wait_time}s (Attempt {retries}/{max_retries})...")
                time.sleep(wait_time)
    
    print("All batches uploaded successfully!")

# run it
safe_upsert(client, collection, anime_points, start_from= 0)

Batch 0/1656 uploaded (0 to 10)
Batch 1/1656 uploaded (10 to 20)
Batch 2/1656 uploaded (20 to 30)
Batch 3/1656 uploaded (30 to 40)
Batch 4/1656 uploaded (40 to 50)
Batch 5/1656 uploaded (50 to 60)
Batch 6/1656 uploaded (60 to 70)
Batch 7/1656 uploaded (70 to 80)
Batch 8/1656 uploaded (80 to 90)
Batch 9/1656 uploaded (90 to 100)
Batch 10/1656 uploaded (100 to 110)
Batch 11/1656 uploaded (110 to 120)
Batch 12/1656 uploaded (120 to 130)
Batch 13/1656 uploaded (130 to 140)
Batch 14/1656 uploaded (140 to 150)
Batch 15/1656 uploaded (150 to 160)
Batch 16/1656 uploaded (160 to 170)
Batch 17/1656 uploaded (170 to 180)
Batch 18/1656 uploaded (180 to 190)
Batch 19/1656 uploaded (190 to 200)
Batch 20/1656 uploaded (200 to 210)
Batch 21/1656 uploaded (210 to 220)
Batch 22/1656 uploaded (220 to 230)
Batch 23/1656 uploaded (230 to 240)
Batch 24/1656 uploaded (240 to 250)
Batch 25/1656 uploaded (250 to 260)
Batch 26/1656 uploaded (260 to 270)
Batch 27/1656 uploaded (270 to 280)
Batch 28/1656 uploaded (280 to 290)
Batch 29/1656 uploaded (290 to 300)
Batch 30/1656 uploaded (300 to 310)
Batch 31/1656 uploaded (310 to 320)
Batch 32/1656 uploaded (320 to 330)
Batch 33/1656 uploaded (330 to 340)
Batch 34/1656 uploaded (340 to 350)
Batch 35/1656 uploaded (350 to 360)
Batch 36/1656 uploaded (360 to 370)
Batch 37/1656 uploaded (370 to 380)
Batch 38/1656 uploaded (380 to 390)
Batch 39/1656 uploaded (390 to 400)
Batch 40/1656 uploaded (400 to 410)
Batch 41/1656 uploaded (410 to 420)
Batch 42/1656 uploaded (420 to 430)
Batch 43/1656 uploaded (430 to 440)
Batch 44/1656 uploaded (440 to 450)
Batch 45/1656 uploaded (450 to 460)
Batch 46/1656 uploaded (460 to 470)
Batch 47/1656 uploaded (470 to 480)
Batch 48/1656 uploaded (480 to 490)
Batch 49/1656 uploaded (490 to 500)
Batch 50/1656 uploaded (500 to 510)
Batch 51/1656 uploaded (510 to 520)
Batch 52/1656 uploaded (520 to 530)
Batch 53/1656 uploaded (530 to 540)
Batch 54/1656 uploaded (540 to 550)
Batch 55/1656 uploaded (550 to 560)
Batch 56/1656 uploaded (560 to 570)
Batch 57/1656 uploaded (570 to 580)
Batch 58/1656 uploaded (580 to 590)
Batch 59/1656 uploaded (590 to 600)
Batch 60/1656 uploaded (600 to 610)
Batch 61/1656 uploaded (610 to 620)
Batch 62/1656 uploaded (620 to 630)
Batch 63/1656 uploaded (630 to 640)
Batch 64/1656 uploaded (640 to 650)
Batch 65/1656 uploaded (650 to 660)
Batch 66/1656 uploaded (660 to 670)
Batch 67/1656 uploaded (670 to 680)
Batch 68/1656 uploaded (680 to 690)
Batch 69/1656 uploaded (690 to 700)
Batch 70/1656 uploaded (700 to 710)
Batch 71/1656 uploaded (710 to 720)
Batch 72/1656 uploaded (720 to 730)
Batch 73/1656 uploaded (730 to 740)
Batch 74/1656 uploaded (740 to 750)
Batch 75/1656 uploaded (750 to 760)
Batch 76/1656 uploaded (760 to 770)
Batch 77/1656 uploaded (770 to 780)
Batch 78/1656 uploaded (780 to 790)
Batch 79/1656 uploaded (790 to 800)
Batch 80/1656 uploaded (800 to 810)
Batch 81/1656 uploaded (810 to 820)
Batch 82/1656 uploaded (820 to 830)
Batch 83/1656 uploaded (830 to 840)
Batch 84/1656 uploaded (840 to 850)
Batch 85/1656 uploaded (850 to 860)
Batch 86/1656 uploaded (860 to 870)
Batch 87/1656 uploaded (870 to 880)
Batch 88/1656 uploaded (880 to 890)
Batch 89/1656 uploaded (890 to 900)
Batch 90/1656 uploaded (900 to 910)
Batch 91/1656 uploaded (910 to 920)
Batch 92/1656 uploaded (920 to 930)
Batch 93/1656 uploaded (930 to 940)
Batch 94/1656 uploaded (940 to 950)
Batch 95/1656 uploaded (950 to 960)
Batch 96/1656 uploaded (960 to 970)
Batch 97/1656 uploaded (970 to 980)
Batch 98/1656 uploaded (980 to 990)
Batch 99/1656 uploaded (990 to 1000)
Batch 100/1656 uploaded (1000 to 1010)
Batch 101/1656 uploaded (1010 to 1020)
Batch 102/1656 uploaded (1020 to 1030)
Batch 103/1656 uploaded (1030 to 1040)
Batch 104/1656 uploaded (1040 to 1050)
Batch 105/1656 uploaded (1050 to 1060)
Batch 106/1656 uploaded (1060 to 1070)
Batch 107/1656 uploaded (1070 to 1080)
Batch 108/1656 uploaded (1080 to 1090)
Batch 109/1656 uploaded (1090 to 1100)
Batch 110/1656 uploaded (1100 to 1110)
Batch 111/1656 uploaded (1110 to 1120)
Batch 112/1656 uploaded (1120 to 1130)
Batch 113/1656 uploaded (1130 to 1140)
Batch 114/1656 uploaded (1140 to 1150)
Batch 115/1656 uploaded (1150 to 1160)
Batch 116/1656 uploaded (1160 to 1170)
Batch 117/1656 uploaded (1170 to 1180)
Batch 118/1656 uploaded (1180 to 1190)
Batch 119/1656 uploaded (1190 to 1200)
Batch 120/1656 uploaded (1200 to 1210)
Batch 121/1656 uploaded (1210 to 1220)
Batch 122/1656 uploaded (1220 to 1230)
Batch 123/1656 uploaded (1230 to 1240)
Batch 124/1656 uploaded (1240 to 1250)
Batch 125/1656 uploaded (1250 to 1260)
Batch 126/1656 uploaded (1260 to 1270)
Batch 127/1656 uploaded (1270 to 1280)
Batch 128/1656 uploaded (1280 to 1290)
Batch 129/1656 uploaded (1290 to 1300)
Batch 130/1656 uploaded (1300 to 1310)
Batch 131/1656 uploaded (1310 to 1320)
Batch 132/1656 uploaded (1320 to 1330)
Batch 133/1656 uploaded (1330 to 1340)
Batch 134/1656 uploaded (1340 to 1350)
Batch 135/1656 uploaded (1350 to 1360)
Batch 136/1656 uploaded (1360 to 1370)
Batch 137/1656 uploaded (1370 to 1380)
Batch 138/1656 uploaded (1380 to 1390)
Batch 139/1656 uploaded (1390 to 1400)
Batch 140/1656 uploaded (1400 to 1410)
Batch 141/1656 uploaded (1410 to 1420)
Batch 142/1656 uploaded (1420 to 1430)
Batch 143/1656 uploaded (1430 to 1440)
Batch 144/1656 uploaded (1440 to 1450)
Batch 145/1656 uploaded (1450 to 1460)
Batch 146/1656 uploaded (1460 to 1470)
Batch 147/1656 uploaded (1470 to 1480)
Batch 148/1656 uploaded (1480 to 1490)
Batch 149/1656 uploaded (1490 to 1500)
Batch 150/1656 uploaded (1500 to 1510)
Batch 151/1656 uploaded (1510 to 1520)
Batch 152/1656 uploaded (1520 to 1530)
Batch 153/1656 uploaded (1530 to 1540)
Batch 154/1656 uploaded (1540 to 1550)
Batch 155/1656 uploaded (1550 to 1560)
Batch 156/1656 uploaded (1560 to 1570)
Batch 157/1656 uploaded (1570 to 1580)
Batch 158/1656 uploaded (1580 to 1590)
Batch 159/1656 uploaded (1590 to 1600)
Batch 160/1656 uploaded (1600 to 1610)
Batch 161/1656 uploaded (1610 to 1620)
Batch 162/1656 uploaded (1620 to 1630)
Batch 163/1656 uploaded (1630 to 1640)
Batch 164/1656 uploaded (1640 to 1650)
Batch 165/1656 uploaded (1650 to 1660)
Batch 166/1656 uploaded (1660 to 1670)
Batch 167/1656 uploaded (1670 to 1680)
Batch 168/1656 uploaded (1680 to 1690)
Batch 169/1656 uploaded (1690 to 1700)
Batch 170/1656 uploaded (1700 to 1710)
Batch 171/1656 uploaded (1710 to 1720)
Batch 172/1656 uploaded (1720 to 1730)
Batch 173/1656 uploaded (1730 to 1740)
Batch 174/1656 uploaded (1740 to 1750)
Batch 175/1656 uploaded (1750 to 1760)
Batch 176/1656 uploaded (1760 to 1770)
Batch 177/1656 uploaded (1770 to 1780)
Batch 178/1656 uploaded (1780 to 1790)
Batch 179/1656 uploaded (1790 to 1800)
Batch 180/1656 uploaded (1800 to 1810)
Batch 181/1656 uploaded (1810 to 1820)
Batch 182/1656 uploaded (1820 to 1830)
Batch 183/1656 uploaded (1830 to 1840)
Batch 184/1656 uploaded (1840 to 1850)
Batch 185/1656 uploaded (1850 to 1860)
Batch 186/1656 uploaded (1860 to 1870)
Batch 187/1656 uploaded (1870 to 1880)
Batch 188/1656 uploaded (1880 to 1890)
Batch 189/1656 uploaded (1890 to 1900)
Batch 190/1656 uploaded (1900 to 1910)
Batch 191/1656 uploaded (1910 to 1920)
Batch 192/1656 uploaded (1920 to 1930)
Batch 193/1656 uploaded (1930 to 1940)
Batch 194/1656 uploaded (1940 to 1950)
Batch 195/1656 uploaded (1950 to 1960)
Batch 196/1656 uploaded (1960 to 1970)
Batch 197/1656 uploaded (1970 to 1980)
Batch 198/1656 uploaded (1980 to 1990)
Batch 199/1656 uploaded (1990 to 2000)
Batch 200/1656 uploaded (2000 to 2010)
Batch 201/1656 uploaded (2010 to 2020)
Batch 202/1656 uploaded (2020 to 2030)
Batch 203/1656 uploaded (2030 to 2040)
Batch 204/1656 uploaded (2040 to 2050)
Batch 205/1656 uploaded (2050 to 2060)
Batch 206/1656 uploaded (2060 to 2070)
Batch 207/1656 uploaded (2070 to 2080)
Batch 208/1656 uploaded (2080 to 2090)
Batch 209/1656 uploaded (2090 to 2100)
Batch 210/1656 uploaded (2100 to 2110)
Batch 211/1656 uploaded (2110 to 2120)
Batch 212/1656 uploaded (2120 to 2130)
Batch 213/1656 uploaded (2130 to 2140)
Batch 214/1656 uploaded (2140 to 2150)
Batch 215/1656 uploaded (2150 to 2160)
Batch 216/1656 uploaded (2160 to 2170)
Batch 217/1656 uploaded (2170 to 2180)
Batch 218/1656 uploaded (2180 to 2190)
Batch 219/1656 uploaded (2190 to 2200)
Batch 220/1656 uploaded (2200 to 2210)
Batch 221/1656 uploaded (2210 to 2220)
Batch 222/1656 uploaded (2220 to 2230)
Batch 223/1656 uploaded (2230 to 2240)
Batch 224/1656 uploaded (2240 to 2250)
Batch 225/1656 uploaded (2250 to 2260)
Batch 226/1656 uploaded (2260 to 2270)
Batch 227/1656 uploaded (2270 to 2280)
Batch 228/1656 uploaded (2280 to 2290)
Batch 229/1656 uploaded (2290 to 2300)
Batch 230/1656 uploaded (2300 to 2310)
Batch 231/1656 uploaded (2310 to 2320)
Batch 232/1656 uploaded (2320 to 2330)
Batch 233/1656 uploaded (2330 to 2340)
Batch 234/1656 uploaded (2340 to 2350)
Batch 235/1656 uploaded (2350 to 2360)
Batch 236/1656 uploaded (2360 to 2370)
Batch 237/1656 uploaded (2370 to 2380)
Batch 238/1656 uploaded (2380 to 2390)
Batch 239/1656 uploaded (2390 to 2400)
Batch 240/1656 uploaded (2400 to 2410)
Batch 241/1656 uploaded (2410 to 2420)
Batch 242/1656 uploaded (2420 to 2430)
Batch 243/1656 uploaded (2430 to 2440)
Batch 244/1656 uploaded (2440 to 2450)
Batch 245/1656 uploaded (2450 to 2460)
Batch 246/1656 uploaded (2460 to 2470)
Batch 247/1656 uploaded (2470 to 2480)
Batch 248/1656 uploaded (2480 to 2490)
Batch 249/1656 uploaded (2490 to 2500)
Batch 250/1656 uploaded (2500 to 2510)
Batch 251/1656 uploaded (2510 to 2520)
Batch 252/1656 uploaded (2520 to 2530)
Batch 253/1656 uploaded (2530 to 2540)
Batch 254/1656 uploaded (2540 to 2550)
Batch 255/1656 uploaded (2550 to 2560)
Batch 256/1656 uploaded (2560 to 2570)
Batch 257/1656 uploaded (2570 to 2580)
Batch 258/1656 uploaded (2580 to 2590)
Batch 259/1656 uploaded (2590 to 2600)
Batch 260/1656 uploaded (2600 to 2610)
Batch 261/1656 uploaded (2610 to 2620)
Batch 262/1656 uploaded (2620 to 2630)
Batch 263/1656 uploaded (2630 to 2640)
Batch 264/1656 uploaded (2640 to 2650)
Batch 265/1656 uploaded (2650 to 2660)
Batch 266/1656 uploaded (2660 to 2670)
Batch 267/1656 uploaded (2670 to 2680)
Batch 268/1656 uploaded (2680 to 2690)
Batch 269/1656 uploaded (2690 to 2700)
Batch 270/1656 uploaded (2700 to 2710)
Batch 271/1656 uploaded (2710 to 2720)
Batch 272/1656 uploaded (2720 to 2730)
Batch 273/1656 uploaded (2730 to 2740)
Batch 274/1656 uploaded (2740 to 2750)
Batch 275/1656 uploaded (2750 to 2760)
Batch 276/1656 uploaded (2760 to 2770)
Batch 277/1656 uploaded (2770 to 2780)
Batch 278/1656 uploaded (2780 to 2790)
Batch 279/1656 uploaded (2790 to 2800)
Batch 280/1656 uploaded (2800 to 2810)
Batch 281/1656 uploaded (2810 to 2820)
Batch 282/1656 uploaded (2820 to 2830)
Batch 283/1656 uploaded (2830 to 2840)
Batch 284/1656 uploaded (2840 to 2850)
Batch 285/1656 uploaded (2850 to 2860)
Batch 286/1656 uploaded (2860 to 2870)
Batch 287/1656 uploaded (2870 to 2880)
Batch 288/1656 uploaded (2880 to 2890)
Batch 289/1656 uploaded (2890 to 2900)
Batch 290/1656 uploaded (2900 to 2910)
Batch 291/1656 uploaded (2910 to 2920)
Batch 292/1656 uploaded (2920 to 2930)
Batch 293/1656 uploaded (2930 to 2940)
Batch 294/1656 uploaded (2940 to 2950)
Batch 295/1656 uploaded (2950 to 2960)
Batch 296/1656 uploaded (2960 to 2970)
Batch 297/1656 uploaded (2970 to 2980)
Batch 298/1656 uploaded (2980 to 2990)
Batch 299/1656 uploaded (2990 to 3000)
Batch 300/1656 uploaded (3000 to 3010)
Batch 301/1656 uploaded (3010 to 3020)
Batch 302/1656 uploaded (3020 to 3030)
Batch 303/1656 uploaded (3030 to 3040)
Batch 304/1656 uploaded (3040 to 3050)
Batch 305/1656 uploaded (3050 to 3060)
Batch 306/1656 uploaded (3060 to 3070)
Batch 307/1656 uploaded (3070 to 3080)
Batch 308/1656 uploaded (3080 to 3090)
Batch 309/1656 uploaded (3090 to 3100)
Batch 310/1656 uploaded (3100 to 3110)
Batch 311/1656 uploaded (3110 to 3120)
Batch 312/1656 uploaded (3120 to 3130)
Batch 313/1656 uploaded (3130 to 3140)
Batch 314/1656 uploaded (3140 to 3150)
Batch 315/1656 uploaded (3150 to 3160)
Batch 316/1656 uploaded (3160 to 3170)
Batch 317/1656 uploaded (3170 to 3180)
Batch 318/1656 uploaded (3180 to 3190)
Batch 319/1656 uploaded (3190 to 3200)
Batch 320/1656 uploaded (3200 to 3210)
Batch 321/1656 uploaded (3210 to 3220)
Batch 322/1656 uploaded (3220 to 3230)
Batch 323/1656 uploaded (3230 to 3240)
Batch 324/1656 uploaded (3240 to 3250)
Batch 325/1656 uploaded (3250 to 3260)
Batch 326/1656 uploaded (3260 to 3270)
Batch 327/1656 uploaded (3270 to 3280)
Batch 328/1656 uploaded (3280 to 3290)
Batch 329/1656 uploaded (3290 to 3300)
Batch 330/1656 uploaded (3300 to 3310)
Batch 331/1656 uploaded (3310 to 3320)
Batch 332/1656 uploaded (3320 to 3330)
Batch 333/1656 uploaded (3330 to 3340)
Batch 334/1656 uploaded (3340 to 3350)
Batch 335/1656 uploaded (3350 to 3360)
Batch 336/1656 uploaded (3360 to 3370)
Batch 337/1656 uploaded (3370 to 3380)
Batch 338/1656 uploaded (3380 to 3390)
Batch 339/1656 uploaded (3390 to 3400)
Batch 340/1656 uploaded (3400 to 3410)
Batch 341/1656 uploaded (3410 to 3420)
Batch 342/1656 uploaded (3420 to 3430)
Batch 343/1656 uploaded (3430 to 3440)
Batch 344/1656 uploaded (3440 to 3450)
Batch 345/1656 uploaded (3450 to 3460)
Batch 346/1656 uploaded (3460 to 3470)
Batch 347/1656 uploaded (3470 to 3480)
Batch 348/1656 uploaded (3480 to 3490)
Batch 349/1656 uploaded (3490 to 3500)
Batch 350/1656 uploaded (3500 to 3510)
Batch 351/1656 uploaded (3510 to 3520)
Batch 352/1656 uploaded (3520 to 3530)
Batch 353/1656 uploaded (3530 to 3540)
Batch 354/1656 uploaded (3540 to 3550)
Batch 355/1656 uploaded (3550 to 3560)
Batch 356/1656 uploaded (3560 to 3570)
Batch 357/1656 uploaded (3570 to 3580)
Batch 358/1656 uploaded (3580 to 3590)
Batch 359/1656 uploaded (3590 to 3600)
Batch 360/1656 uploaded (3600 to 3610)
Batch 361/1656 uploaded (3610 to 3620)
Batch 362/1656 uploaded (3620 to 3630)
Batch 363/1656 uploaded (3630 to 3640)
Batch 364/1656 uploaded (3640 to 3650)
Batch 365/1656 uploaded (3650 to 3660)
Batch 366/1656 uploaded (3660 to 3670)
Batch 367/1656 uploaded (3670 to 3680)
Batch 368/1656 uploaded (3680 to 3690)
Batch 369/1656 uploaded (3690 to 3700)
Batch 370/1656 uploaded (3700 to 3710)
Batch 371/1656 uploaded (3710 to 3720)
Batch 372/1656 uploaded (3720 to 3730)
Batch 373/1656 uploaded (3730 to 3740)
Batch 374/1656 uploaded (3740 to 3750)
Batch 375/1656 uploaded (3750 to 3760)
Batch 376/1656 uploaded (3760 to 3770)
Batch 377/1656 uploaded (3770 to 3780)
Batch 378/1656 uploaded (3780 to 3790)
Batch 379/1656 uploaded (3790 to 3800)
Batch 380/1656 uploaded (3800 to 3810)
Batch 381/1656 uploaded (3810 to 3820)
Batch 382/1656 uploaded (3820 to 3830)
Batch 383/1656 uploaded (3830 to 3840)
Batch 384/1656 uploaded (3840 to 3850)
Batch 385/1656 uploaded (3850 to 3860)
Batch 386/1656 uploaded (3860 to 3870)
Batch 387/1656 uploaded (3870 to 3880)
Batch 388/1656 uploaded (3880 to 3890)
Batch 389/1656 uploaded (3890 to 3900)
Batch 390/1656 uploaded (3900 to 3910)
Batch 391/1656 uploaded (3910 to 3920)
Batch 392/1656 uploaded (3920 to 3930)
Batch 393/1656 uploaded (3930 to 3940)
Batch 394/1656 uploaded (3940 to 3950)
Batch 395/1656 uploaded (3950 to 3960)
Batch 396/1656 uploaded (3960 to 3970)
Batch 397/1656 uploaded (3970 to 3980)
Batch 398/1656 uploaded (3980 to 3990)
Batch 399/1656 uploaded (3990 to 4000)
Batch 400/1656 uploaded (4000 to 4010)
Batch 401/1656 uploaded (4010 to 4020)
Batch 402/1656 uploaded (4020 to 4030)
Batch 403/1656 uploaded (4030 to 4040)
Batch 404/1656 uploaded (4040 to 4050)
Batch 405/1656 uploaded (4050 to 4060)
Batch 406/1656 uploaded (4060 to 4070)
Batch 407/1656 uploaded (4070 to 4080)
Batch 408/1656 uploaded (4080 to 4090)
Batch 409/1656 uploaded (4090 to 4100)
Batch 410/1656 uploaded (4100 to 4110)
Batch 411/1656 uploaded (4110 to 4120)
Batch 412/1656 uploaded (4120 to 4130)
Batch 413/1656 uploaded (4130 to 4140)
Batch 414/1656 uploaded (4140 to 4150)
Batch 415/1656 uploaded (4150 to 4160)
Batch 416/1656 uploaded (4160 to 4170)
Batch 417/1656 uploaded (4170 to 4180)
Batch 418/1656 uploaded (4180 to 4190)
Batch 419/1656 uploaded (4190 to 4200)
Batch 420/1656 uploaded (4200 to 4210)
Batch 421/1656 uploaded (4210 to 4220)
Batch 422/1656 uploaded (4220 to 4230)
Batch 423/1656 uploaded (4230 to 4240)
Batch 424/1656 uploaded (4240 to 4250)
Batch 425/1656 uploaded (4250 to 4260)
Batch 426/1656 uploaded (4260 to 4270)
Batch 427/1656 uploaded (4270 to 4280)
Batch 428/1656 uploaded (4280 to 4290)
Batch 429/1656 uploaded (4290 to 4300)
Batch 430/1656 uploaded (4300 to 4310)
Batch 431/1656 uploaded (4310 to 4320)
Batch 432/1656 uploaded (4320 to 4330)
Batch 433/1656 uploaded (4330 to 4340)
Batch 434/1656 uploaded (4340 to 4350)
Batch 435/1656 uploaded (4350 to 4360)
Batch 436/1656 uploaded (4360 to 4370)
Batch 437/1656 uploaded (4370 to 4380)
Batch 438/1656 uploaded (4380 to 4390)
Batch 439/1656 uploaded (4390 to 4400)
Batch 440/1656 uploaded (4400 to 4410)
Batch 441/1656 uploaded (4410 to 4420)
Batch 442/1656 uploaded (4420 to 4430)
Batch 443/1656 uploaded (4430 to 4440)
Batch 444/1656 uploaded (4440 to 4450)
Batch 445/1656 uploaded (4450 to 4460)
Batch 446/1656 uploaded (4460 to 4470)
Batch 447/1656 uploaded (4470 to 4480)
Batch 448/1656 uploaded (4480 to 4490)
Batch 449/1656 uploaded (4490 to 4500)
Batch 450/1656 uploaded (4500 to 4510)
Batch 451/1656 uploaded (4510 to 4520)
Batch 452/1656 uploaded (4520 to 4530)
Batch 453/1656 uploaded (4530 to 4540)
Batch 454/1656 uploaded (4540 to 4550)
Batch 455/1656 uploaded (4550 to 4560)
Batch 456/1656 uploaded (4560 to 4570)
Batch 457/1656 uploaded (4570 to 4580)
Batch 458/1656 uploaded (4580 to 4590)
Batch 459/1656 uploaded (4590 to 4600)
Batch 460/1656 uploaded (4600 to 4610)
Batch 461/1656 uploaded (4610 to 4620)
Batch 462/1656 uploaded (4620 to 4630)
Batch 463/1656 uploaded (4630 to 4640)
Batch 464/1656 uploaded (4640 to 4650)
Batch 465/1656 uploaded (4650 to 4660)
Batch 466/1656 uploaded (4660 to 4670)
Batch 467/1656 uploaded (4670 to 4680)
Batch 468/1656 uploaded (4680 to 4690)
Batch 469/1656 uploaded (4690 to 4700)
Batch 470/1656 uploaded (4700 to 4710)
Batch 471/1656 uploaded (4710 to 4720)
Batch 472/1656 uploaded (4720 to 4730)
Batch 473/1656 uploaded (4730 to 4740)
Batch 474/1656 uploaded (4740 to 4750)
Batch 475/1656 uploaded (4750 to 4760)
Batch 476/1656 uploaded (4760 to 4770)
Batch 477/1656 uploaded (4770 to 4780)
Batch 478/1656 uploaded (4780 to 4790)
Batch 479/1656 uploaded (4790 to 4800)
Batch 480/1656 uploaded (4800 to 4810)
Batch 481/1656 uploaded (4810 to 4820)
Batch 482/1656 uploaded (4820 to 4830)
Batch 483/1656 uploaded (4830 to 4840)
Batch 484/1656 uploaded (4840 to 4850)
Batch 485/1656 uploaded (4850 to 4860)
Batch 486/1656 uploaded (4860 to 4870)
Batch 487/1656 uploaded (4870 to 4880)
Batch 488/1656 uploaded (4880 to 4890)
Batch 489/1656 uploaded (4890 to 4900)
Batch 490/1656 uploaded (4900 to 4910)
Batch 491/1656 uploaded (4910 to 4920)
Batch 492/1656 uploaded (4920 to 4930)
Batch 493/1656 uploaded (4930 to 4940)
Batch 494/1656 uploaded (4940 to 4950)
Batch 495/1656 uploaded (4950 to 4960)
Batch 496/1656 uploaded (4960 to 4970)
Batch 497/1656 uploaded (4970 to 4980)
Batch 498/1656 uploaded (4980 to 4990)
Batch 499/1656 uploaded (4990 to 5000)
Batch 500/1656 uploaded (5000 to 5010)
Batch 501/1656 uploaded (5010 to 5020)
Batch 502/1656 uploaded (5020 to 5030)
Batch 503/1656 uploaded (5030 to 5040)
Batch 504/1656 uploaded (5040 to 5050)
Batch 505/1656 uploaded (5050 to 5060)
Batch 506/1656 uploaded (5060 to 5070)
Batch 507/1656 uploaded (5070 to 5080)
Batch 508/1656 uploaded (5080 to 5090)
Batch 509/1656 uploaded (5090 to 5100)
Batch 510/1656 uploaded (5100 to 5110)
Batch 511/1656 uploaded (5110 to 5120)
Batch 512/1656 uploaded (5120 to 5130)
Batch 513/1656 uploaded (5130 to 5140)
Batch 514/1656 uploaded (5140 to 5150)
Batch 515/1656 uploaded (5150 to 5160)
Batch 516/1656 uploaded (5160 to 5170)
Batch 517/1656 uploaded (5170 to 5180)
Batch 518/1656 uploaded (5180 to 5190)
Batch 519/1656 uploaded (5190 to 5200)
Batch 520/1656 uploaded (5200 to 5210)