In [1]:
import pandas as pd 
import re

In [2]:
anime = pd.read_csv("animes.csv")

In [3]:
meta = pd.read_csv("cleaned_metadata1.csv")

In [11]:
anime.sample(50)

,animeID,title,alternative_title,type,year,score,episodes,mal_url,sequel,image_url,genres,genres_detailed
18294,18295,Kensaku to Enjin no Happy Birthday,NaN,ONA,2018,6.07,1,https://myanimelist.net/anime/38785,False,https://cdn.myanimelist.net/images/anime/1613/...,['Sci-Fi'],"['cg animation', 'family friendly', 'kids', 'n..."
73,74,Pokémon,Pokemon,TV,1997,7.41,276,https://myanimelist.net/anime/527,False,https://cdn.myanimelist.net/images/anime/1787/...,"['Action', 'Adventure', 'Comedy', 'Fantasy']","['absurdist humour', 'action', 'adventure', 'a..."
15957,15958,Cai Mogu,NaN,MOVIE,1953,5.41,1,https://myanimelist.net/anime/43212,False,https://cdn.myanimelist.net/images/anime/1964/...,['Avant Garde'],"['adventure', 'animal protagonists', 'anthropo..."
17815,17816,Ba Luo Bo,NaN,MOVIE,1957,5.69,1,https://myanimelist.net/anime/48979,False,https://cdn.myanimelist.net/images/anime/1781/...,['Comedy'],"['animal protagonists', 'anthropomorphic', 'ch..."
17468,17469,Hello Kitty in Snow White,Hello Kitty no Shirayuki-hime,OVA,1993,5.5,1,https://myanimelist.net/anime/17951,False,https://cdn.myanimelist.net/images/anime/2/478...,['Fantasy'],"['animal protagonists', 'anthropomorphic', 'an..."
9722,9723,Ero Manga! H mo Manga mo Step-up♪,NaN,OVA,2015,6.34,2,https://myanimelist.net/anime/31788,False,https://cdn.myanimelist.net/images/anime/1245/...,['Hentai'],"['adult audience only', 'comedy', 'hentai', 'm..."
11305,11306,Youkai Watch Movie 3: Soratobu Kujira to Doubl...,NaN,MOVIE,2016,6.2,1,https://myanimelist.net/anime/32222,False,https://cdn.myanimelist.net/images/anime/10/86...,"['Comedy', 'Supernatural']","['based on a video game', 'cg animation', 'com..."
17904,17905,Pochama Sweets,NaN,SPECIAL,2021,5.82,1,https://myanimelist.net/anime/51018,False,https://cdn.myanimelist.net/images/anime/1640/...,['Comedy'],"['animal protagonists', 'birds', 'comedy', 'fo..."
10616,10617,Hello Kitty in Cinderella,Hello Kitty no Cinderella,MOVIE,1989,6.05,1,https://myanimelist.net/anime/9291,False,https://cdn.myanimelist.net/images/anime/9/724...,['Fantasy'],"['animal protagonists', 'animals', 'anthropomo..."
3881,3882,Yamada-kun to 7-nin no Majo PV,NaN,SPECIAL,2013,7.18,1,https://myanimelist.net/anime/20359,False,https://cdn.myanimelist.net/images/anime/8/588...,"['Comedy', 'Supernatural']","['based on a manga', 'body swapping', 'comedy'..."
9858,9859,Mobile Suit SD Gundam Mk-V,Kidou Senshi SD Gundam Mk-V,OVA,1990,5.64,3,https://myanimelist.net/anime/6792,False,https://cdn.myanimelist.net/images/anime/1724/...,"['Action', 'Comedy', 'Sci-Fi']","['action', 'adventure', 'chibi', 'chibi style'..."
18900,18901,Wind Breaker Season 2,NaN,TV,2025,8,12,https://myanimelist.net/anime/59160,True,https://cdn.myanimelist.net/images/anime/1526/...,['Action'],"['action', 'based on a manga', 'bullying', 'cg..."
13161,13162,Sasuke,NaN,TV,1968,6.84,29,https://myanimelist.net/anime/6056,False,https://cdn.myanimelist.net/images/anime/4/308...,['Action'],"['action', 'adventure', 'asia', 'based on a ma..."
2920,2921,IGPX: Immortal Grand Prix Season 2,IGPX: Immortal Grand Prix (2005) 2nd Season,TV,2006,7.27,13,https://myanimelist.net/anime/1410,False,https://cdn.myanimelist.net/images/anime/3/217...,"['Action', 'Sci-Fi']","['action', 'cars', 'mecha', 'motorsport', 'ori..."
17046,17047,Crayon Shin-chan: Arashi wo Yobu Kasukabe Boue...,NaN,MOVIE,2011,7.15,1,https://myanimelist.net/anime/53969,False,https://cdn.myanimelist.net/images/anime/1110/...,"['Comedy', 'Sci-Fi']","['comedy', 'family friendly', 'kids', 'school'..."
11368,11369,Grendizer: Getter Robo G - Great Mazinger Kess...,NaN,MOVIE,1976,6.36,1,https://myanimelist.net/anime/3481,False,https://cdn.myanimelist.net/images/anime/1125/...,"['Action', 'Sci-Fi']","['action', 'adventure', 'asia', 'calling your ..."
11287,11288,Giant Gorg,NaN,TV,1984,7.13,26,https://myanimelist.net/anime/3327,False,https://cdn.myanimelist.net/images/anime/1784/...,"['Action', 'Adventure', 'Sci-Fi']","['action', 'adventure', 'alien', 'aliens', 'am..."
10251,10252,Kyonyuu Try!: Tanki Shuuchuu Chichi Momi Lesson,NaN,OVA,2014,6.24,1,https://myanimelist.net/anime/24911,False,https://cdn.myanimelist.net/images/anime/1253/...,['Hentai'],"['adult audience only', 'hentai', 'present']"
14524,14525,Nanami-chan 3rd Series,NaN,TV,2006,5.64,16,https://myanimelist.net/anime/4316,False,https://cdn.myanimelist.net/images/anime/12/64...,['Comedy'],"['animal protagonists', 'comedy', 'dogs', 'fam..."
2271,2272,Fantastic Children,NaN,TV,2004,7.49,26,https://myanimelist.net/anime/455,False,https://cdn.myanimelist.net/images/anime/9/770...,"['Adventure', 'Fantasy', 'Mystery', 'Romance',...","['action', 'adventure', 'age regression', 'ali..."
19551,19552,Just Esperia Things,Jian Yu Yuanzheng: Insomnia De Naxie Shier,ONA,2022,5.82,12,https://myanimelist.net/anime/53055,False,https://cdn.myanimelist.net/images/anime/1535/...,"['Comedy', 'Fantasy']","['based on a mobile game', 'chinese animation'..."
10683,10684,King of Breasts,Oppai no Ouja 48,OVA,2010,6.96,2,https://myanimelist.net/anime/8039,False,https://cdn.myanimelist.net/images/anime/7/195...,['Hentai'],"['adult audience only', 'comedy', 'erotica', '..."
11548,11549,Shinobanai! Crypto Ninja Sakuya,NaN,TV,2023,4.73,13,https://myanimelist.net/anime/56505,False,https://cdn.myanimelist.net/images/anime/1367/...,['Action'],"['action', 'chibi', 'comedy', 'historical', 'i..."
18792,18793,Moshi Meta: Moshi Joshikousei ga Metaverse de ...,NaN,ONA,2023,5.18,1,https://myanimelist.net/anime/55301,False,https://cdn.myanimelist.net/images/anime/1195/...,['Sci-Fi'],"['anime tamago', 'animenotane', 'japanese prod..."
9473,9474,Kakyusei 2,Kakyuusei 2: Hitomi no Naka no Shoujo-tachi,TV,2004,5.76,13,https://myanimelist.net/anime/510,False,https://cdn.myanimelist.net/images/anime/1643/...,"['Comedy', 'Drama', 'Romance']","['android', 'asia', 'based on a visual novel',..."
8487,8488,Boku to Sensei to Tomodachi no Mama,NaN,OVA,2019,5.53,2,https://myanimelist.net/anime/39803,False,https://cdn.myanimelist.net/images/anime/1011/...,['Hentai'],"['adult audience only', 'hentai', 'present']"
16310,16311,Zero Seiki Movie 1: Emeraldas,NaN,MOVIE,?,5,1,https://myanimelist.net/anime/35853,False,https://cdn.myanimelist.net/images/anime/11/86...,[],"['action', 'adventure', 'leijiverse', 'outer s..."
13749,13750,Nanocore 3rd Season,NaN,ONA,2017,6.38,20,https://myanimelist.net/anime/36571,False,https://cdn.myanimelist.net/images/anime/13/88...,"['Action', 'Adventure', 'Sci-Fi']","['action', 'adventure', 'cg animation', 'cg-an..."
3168,3169,Diabolik Lovers Recap,NaN,SPECIAL,2013,5.42,1,https://myanimelist.net/anime/20919,False,https://cdn.myanimelist.net/images/anime/9/556...,"['Drama', 'Supernatural']","['based on a visual novel', 'based on an otome..."
7418,7419,A Record of a Mortal's Journey to Immortality ...,Fanren Xiu Xian Chuan 2nd Season,ONA,2021,7.98,51,https://myanimelist.net/anime/50207,False,https://cdn.myanimelist.net/images/anime/1875/...,"['Action', 'Adventure', 'Fantasy']","['3d cg animation', 'action', 'adventure', 'bl..."
11446,11447,Ochibi-san,NaN,TV,2023,6.32,24,https://myanimelist.net/anime/56588,False,https://cdn.myanimelist.net/images/anime/1476/...,['Slice of Life'],"['animals', 'anthropomorphic', 'based on a man..."
15438,15439,Omoide no Album,NaN,SPECIAL,1981,4.88,1,https://myanimelist.net/anime/8729,False,https://cdn.myanimelist.net/images/anime/13/24...,['Slice of Life'],"['family friendly', 'japanese production', 'ki..."
4534,4535,MapleStory,NaN,TV,2007,4.45,25,https://myanimelist.net/anime/2719,False,https://cdn.myanimelist.net/images/anime/3/486...,"['Action', 'Adventure', 'Comedy', 'Fantasy']","['action', 'adventure', 'alternative world', '..."
9289,9290,Adults Dunno How to Love!,Otona nya Koi no Shikata ga Wakaranee!,ONA,2020,5.46,8,https://myanimelist.net/anime/42714,False,https://cdn.myanimelist.net/images/anime/1603/...,['Hentai'],"['adult audience only', 'adult couples', 'anim..."
7051,7052,Uncharted Walker,Mi Yu Xingzhe,ONA,2018,7.34,12,https://myanimelist.net/anime/37175,False,https://cdn.myanimelist.net/images/anime/1869/...,"['Mystery', 'Suspense']","['action', 'americas', 'amnesia', 'battle roya..."
5695,5696,"Boku no Imouto wa ""Osaka Okan"": Uchi no Oniich...",NaN,SPECIAL,2013,5.81,1,https://myanimelist.net/anime/18419,False,https://cdn.myanimelist.net/images/anime/9/493...,['Comedy'],"['comedy', 'flash animation', 'original work',..."
380,381,Kaze no Stigma,NaN,TV,2007,7.36,24,https://myanimelist.net/anime/1691,False,https://cdn.myanimelist.net/images/anime/1558/...,"['Action', 'Romance', 'Supernatural']","['action', 'action comedy', 'alternative prese..."
9446,9447,Menhera Ayuri no Yamanai Onedari: Headphone wa...,NaN,OVA,2017,5.54,2,https://myanimelist.net/anime/35343,False,https://cdn.myanimelist.net/images/anime/1085/...,['Hentai'],"['adult audience only', 'comedy', 'hentai', 'h..."
18114,18115,Shounen Sunday CM: Karakuri Circus,NaN,SPECIAL,1998,5.96,1,https://myanimelist.net/anime/40340,False,https://cdn.myanimelist.net/images/anime/1533/...,"['Action', 'Mystery']","['action', 'based on a manga', 'commercials', ..."
13458,13459,Hamtaro: Hamtaro's Birthday! - 3000 Hammy Step...,Tottoko Hamtarou OVA 1: Hamtaro no Otanjoubi -...,OVA,2002,6.37,1,https://myanimelist.net/anime/2399,False,https://cdn.myanimelist.net/images/anime/4/354...,"['Adventure', 'Comedy']","['adventure', 'animal protagonists', 'animals'..."
8347,8348,Laid-Back Camp Season 2 Specials,Yuru Camp△ Season 2 Specials,SPECIAL,2021,7.54,2,https://myanimelist.net/anime/49026,True,https://cdn.myanimelist.net/images/anime/1542/...,['Slice of Life'],"['based on a manga', 'cgdct', 'comedy', 'comin..."
827,828,Chihayafuru,NaN,TV,2011,8.16,25,https://myanimelist.net/anime/10800,False,https://cdn.myanimelist.net/images/anime/3/357...,"['Drama', 'Sports']","['adapted into japanese movie', 'adapted into ..."
11552,11553,Duel Masters Cross Shock,NaN,TV,2010,5.65,50,https://myanimelist.net/anime/10528,False,https://cdn.myanimelist.net/images/anime/1053/...,"['Action', 'Adventure', 'Comedy', 'Fantasy']","['action', 'adventure', 'based on a manga', 'b..."
3967,3968,Mobile Suit Gundam SEED: After-Phase Between t...,Kidou Senshi Gundam SEED: Hoshi no Hazama de,SPECIAL,2004,6.84,1,https://myanimelist.net/anime/2298,False,https://cdn.myanimelist.net/images/anime/7/282...,"['Action', 'Drama', 'Sci-Fi']","['action', 'action drama', 'adventure', 'drama..."
8331,8332,Kyuuseishu,NaN,SPECIAL,2023,7.12,1,https://myanimelist.net/anime/56095,False,https://cdn.myanimelist.net/images/anime/1166/...,"['Comedy', 'Romance']","['angels', 'music', 'psychological']"
11303,11304,Battle Spirits: Saga Brave,NaN,ONA,2019,7.02,3,https://myanimelist.net/anime/38916,True,https://cdn.myanimelist.net/images/anime/1275/...,"['Adventure', 'Sci-Fi']","['action', 'adventure', 'based on a card game'..."
10645,10646,Hunch Gray,Kangurei,SPECIAL,2020,6.82,1,https://myanimelist.net/anime/44084,False,https://cdn.myanimelist.net/images/anime/1946/...,['Fantasy'],"['action', 'childhood friends', 'independent a..."
9792,9793,Let's Destroy the Idol Dream,Oretachi Majikou Destroy,SPECIAL,2021,5.97,1,https://myanimelist.net/anime/52078,False,https://cdn.myanimelist.net/images/anime/1108/...,['Comedy'],"['based on a manga', 'comedy', 'dancing', 'ido..."
3027,3028,The Anthem of the Heart,Kokoro ga Sakebitagatterunda.,MOVIE,2015,7.94,1,https://myanimelist.net/anime/28725,False,https://cdn.myanimelist.net/images/anime/1245/...,"['Drama', 'Romance']","['adapted into japanese movie', 'adapted into ..."
14189,14190,King Fang,Daisetsusan no Yuusha Kibaou,SPECIAL,1978,6.06,1,https://myanimelist.net/anime/6202,False,https://cdn.myanimelist.net/images/anime/1953/...,"['Adventure', 'Drama']","['action', 'adventure', 'animal protagonists',..."

In [4]:
def anime_id(df) :
    match = re.search(r"\d+", df)
    if match:
        return match.group() 
    return None

In [5]:
anime["mal_url"] = anime["mal_url"].apply(anime_id)

In [6]:
anime = anime[["animeID","mal_url"]]

In [7]:
anime["mal_url"] = anime["mal_url"].astype(int)

In [8]:
anime.info()

<class 'pandas.DataFrame'>
RangeIndex: 20237 entries, 0 to 20236
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   animeID  20237 non-null  int64
 1   mal_url  20237 non-null  int64
dtypes: int64(2)
memory usage: 316.3 KB

In [10]:
df = pd.read_csv("ratings.csv")

In [11]:
df

            userID  animeID  rating
0                1        1      10
1                1        2      10
2                1        3       7
3                1        4      10
4                1        5      10
...            ...      ...     ...
148170491  1774522      394       7
148170492  1774522      422       7
148170493  1774522     1018       7
148170494  1774522      590       6
148170495  1774522      230       5

[148170496 rows x 3 columns]

In [12]:
df = df.merge(anime, on= "animeID",how= "left")

In [13]:
df.drop(columns= "animeID", inplace= True)

In [67]:
df3["mal_url"].nunique()

18027

In [19]:
df3 = pd.read_csv("ratings4.csv")

In [15]:
meta.info()

<class 'pandas.DataFrame'>
RangeIndex: 155839 entries, 0 to 155838
Data columns (total 20 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               155839 non-null  int64
 1   idMal            155839 non-null  int64
 2   title            155839 non-null  str
 3   type             155839 non-null  str
 4   format           155839 non-null  str
 5   status           155839 non-null  str
 6   seasonYear       155839 non-null  float64
 7   episodes         155839 non-null  float64
 8   chapters         155839 non-null  float64
 9   volumes          155839 non-null  float64
 10  averageScore     155839 non-null  float64
 11  popularity       155839 non-null  int64
 12  trending         155839 non-null  int64
 13  description      121297 non-null  str
 14  genres           155839 non-null  str
 15  studios          155839 non-null  str
 16  isAdult          155839 non-null  bool
 17  source           155839 non-null  str
 18  countryOfOrigin  155839 non-null  str
 19  stats            155839 non-null  int64
dtypes: bool(1), float64(5), int64(5), str(9)
memory usage: 69.4 MB

In [65]:
# Only keep the join key and the specific columns you actually need (e.g., 'title', 'genres')
meta2 = meta[meta["type"] == "ANIME"]
meta_subset1 = meta2[["id","idMal"]]
# Now the merge is lightweight
final_df1 = df3.merge(meta_subset1, left_on="mal_url", right_on="idMal", how="left")

In [66]:
final_df2["id"].nunique()

16563

In [40]:
final_df1.drop(columns= ["mal_url","idMal"],inplace= True)

In [54]:
final_df2 = final_df1.dropna(subset=["id", "userID", "rating"])

In [ ]:
type_mapping = {
    "userID": "int32",
    "rating": "int8",
    "id": "int32"
}

# Apply it to the dataframe in one shot
final_df1 = final_df1.astype(type_mapping)

In [64]:
final_df_clean.to_csv("ratings11.csv" , index= False)

In [ ]:
final_df2 = final_df1.dropna(subset=["id", "userID", "rating"])

In [55]:
final_df2.info()

<class 'pandas.DataFrame'>
Index: 70520082 entries, 0 to 70674832
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   userID  int64
 1   rating  int64
 2   id      float64
dtypes: float64(1), int64(2)
memory usage: 2.1 GB

In [57]:
import gc

# 1. Create the new cleaned dataframe
final_df_clean = final_df1.dropna(subset=["id", "userID", "rating"])

# 2. Explicitly delete the old, bloated dataframe from memory
del final_df1

# 3. Force Python to empty the trash immediately
gc.collect() 

# 4. Now proceed with your type casting
type_mapping = {"userID": "int32", "rating": "int8", "id": "int32"}
final_df_clean = final_df_clean.astype(type_mapping)

In [61]:
final_df_clean["id"].nunique()

16563

In [63]:
final_df2["id"].nunique()

16563

In [33]:
df2.to_csv("ratings4.csv",index= False)

In [49]:
df.groupby("userID")["rating"].count()

userID
1          101
2           73
3           61
4           70
5          463
          ...
1774518     16
1774519    248
1774520     87
1774521      5
1774522     17
Name: rating, Length: 1774522, dtype: int64

In [21]:
# Creates a row-by-row mask and filters instantly
df[df.groupby("userID")["rating"].transform("count") > 600]

            userID  rating  mal_url
29757947    677871       5    35847
29757948    677871       8    37786
29757949    677871       7    37221
29757950    677871       7    36317
29757951    677871       6    37496
...            ...     ...      ...
148169595  1774509       4    57099
148169596  1774509       4    57217
148169597  1774509       4    57567
148169598  1774509       4    58488
148169599  1774509       3       96

[22649220 rows x 3 columns]

In [21]:
df.drop(df[df.groupby("userID")["rating"].transform("count") > 600].index, inplace = True)

In [22]:
df.drop_duplicates(inplace= True)

In [29]:
df2[''].unique()

array([      1,       2,       3, ..., 1774518, 1774520, 1774522],
      shape=(1000000,))

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 123891979 entries, 0 to 148170495
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   userID   int64
 1   rating   int64
 2   mal_url  int64
dtypes: int64(3)
memory usage: 3.7 GB

In [27]:
unique_users = df['userID'].unique()

sampled_users = pd.Series(unique_users).sample(n=1000000, random_state=42)

df2 = df[df['userID'].isin(sampled_users)]

In [25]:
148170495
14167696
df.info()

<class 'pandas.DataFrame'>
Index: 21160897 entries, 3282 to 148169622
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   userID   int64
 1   rating   int64
 2   mal_url  int64
dtypes: int64(3)
memory usage: 645.8 MB

In [14]:
df.drop_duplicates(inplace= True)

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 21160897 entries, 3282 to 148169622
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   userID   int64
 1   rating   int64
 2   mal_url  int64
dtypes: int64(3)
memory usage: 645.8 MB

In [26]:
df.to_csv("new_ratings.csv", index= False)

In [2]:
df = pd.read_csv("new_ratings")

In [4]:
df.to_csv("new_rating.csv", index= False)

In [7]:
# checking

In [9]:
df.loc[: "userID"].nunique()

userID     1774522
animeID      20237
rating          11
dtype: int64

In [10]:
df.drop_duplicates(inplace= True)

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 144840609 entries, 0 to 148170495
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   userID   int64
 1   animeID  int64
 2   rating   int64
dtypes: int64(3)
memory usage: 4.3 GB